refactor + cleanup
fond-of/spryker-discount pull request #1
Opened 2020-11-04 16:09 UTC by DerCalli

2020-11-05 07:47 UTC, sourcecube reviewed
IMHO `Discount` and `FilteredCalculator` could be done in composition, otherwise the classes get quite complex and are probably harder to update.

2020-11-09 08:32 UTC, daniel-rose requested changes

2020-11-09 08:32 UTC, daniel-rose commented on src/FondOfSpryker/Shared/Discount/Transfer/discount_custom_message.transfer.xml
> +        <property name="usedNotAppliedDiscount" type="Discount[]"/>
<property name="usedNotAppliedDiscounts" singular="usedNotAppliedDiscount" type="Discount[]"/> --> Would be better

2020-11-09 08:32 UTC, daniel-rose commented on src/FondOfSpryker/Zed/Discount/Business/DiscountFacade.php
> +class DiscountFacade extends SprykerDiscountFacade implements DiscountFacadeInterface
Empty class!?

2020-11-09 08:32 UTC, daniel-rose commented on src/FondOfSpryker/Zed/Discount/Business/DiscountFacadeInterface.php
> +interface DiscountFacadeInterface extends SprykerDiscountFacadeInterface
Empty class!?

2020-11-09 08:32 UTC, daniel-rose commented on src/FondOfSpryker/Zed/Discount/Dependency/Form.php
> +class Form
Empty class!?

2020-11-09 08:32 UTC, daniel-rose commented on src/FondOfSpryker/Zed/Discount/Dependency/Persistence.php
> +class Persistence
Empty class!?

2020-11-13 10:16 UTC, merged